version: '3.4'

services:
  mercure:
    image: dunglas/mercure
    environment:
      JWT_KEY: myJWTKey
      DEMO: 1
      ALLOW_ANONYMOUS: 1
      PUBLISH_ALLOWED_ORIGINS: http://localhost
      CORS_ALLOWED_ORIGINS: '*'
    ports:
     - '9000:80'

  server:
   build: docker/gentoo
   hostname: default.random.net
   depends_on:
     - mercure

  node:
    build: .
    ports:
      - '9100:8080'
    environment:
      HOST: 0.0.0.0
    depends_on:
      - mercure
