version: '3.4'

services:
  mercure:
    image: dunglas/mercure
    environment:
      JWT_KEY: testKey
      DEMO: 1
      ALLOW_ANONYMOUS: 1
      PUBLISH_ALLOWED_ORIGINS: http://localhost
    ports:
     - '8080:80'

  server:
   build: docker/gentoo
   hostname: nx-default.nexylan.net

  node:
    build: .
    ports:
      - '8081:8080'
    environment:
      HOST: 0.0.0.0
    depends_on:
      - mercure
